import Head from 'next/head'
import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import gsap from 'gsap'

export default function Home() {
  const intro = useRef()
  const title = useRef()
  const content = useRef()
  const audio = useRef()

  const [playing, setplaying] = useState(false);

  useEffect(() => {
    let tl = new gsap.timeline()

    tl
      .to(intro.current, { opacity: 1, delay: 1, duration: 5.5 })
      .to(intro.current, { 
        opacity: 0, 
        duration: 1.5,
        onComplete: () => {
          audio.current.play(); // autoplay the theme music
        }
      })
      .set(title.current, { opacity: 1, scale: 5, rotate:720})
      .to(title.current, { scale: 0.05, ease: 'power2', duration: 8 ,rotate:0})
      .to(title.current, { opacity: 0, duration: 1.5 }, '-=1.5')
      .set(content.current, { opacity: 1 })
      .to(content.current, { top: '-800%', duration: 100 })
  }, []);

  return (
    <div className='h-screen w-screen flex justify-center items-center'>
      <Head>
        <title>Trajan wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-white z-[200] container">
        <audio ref={audio} muted>
          <source
            type="audio/mpeg" src="https://ia801501.us.archive.org/23/items/StarWars_20180709/Star%20Wars.mp3" />
        </audio>
        <div
          className="bg-transparent z-[100] border-0 bottom-[10px] left-[10px] absolute"
          type="button"
          onClick={() => {
            audio.current.muted = playing;
            setplaying(!playing)
          }}
        >
          {playing ? (
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
            </svg>
          ) : (
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" clipRule="evenodd" />
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2" />
            </svg>
          )}
        </div>
        <section className='transition-all text-center item text-[#4bd5ee] text-[1.25rem]' ref={intro}>
          A long time ago, in miss Lindsay&apos;s <br />classics class...
        </section>

        <section className='flex justify-center w-[18rem] item' ref={title}>
          <img src="https://miro.medium.com/max/1400/1*0_2BBM093Momtv-lrmy62A.png" alt="trajan title" />
        </section>
        <div style={{ perspective: 300 + 'px' }} className="">
          <section className="font-[400] text-yellow-500 rotator text-[300%] left-[50%] absolute bottom-0 h-[80vh] w-[70%]">
            <div className='absolute top-[170%]' ref={content}>
              <h1 className='mb-[5rem] text-center font-[600] font-[Saira_Extra_Condensed]'>Episode LXIX</h1>
              <h2 className='mb-[7rem] scale-[115%] text-center font-[500]'>THE ARCH OF TRAJAN</h2>
              <p className='text-left'><div className="flex">Beneventum. A lowly, unremarkable town that was once the prided entrance to the highway to the port of Brundisium. The Via Traiana. <img className='ml-5' src="https://www.wanderingitaly.com/maps/via-appia-traiana.png" alt="" /></div> <br/>
              One of the best preserved triumphal arches stands tall there, the Arch Of Trajan. 
                <br/><br/>
                <div className="flex">
                <img className='mr-5' src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Benevento-Arch_of_Trajan_from_South.jpg/340px-Benevento-Arch_of_Trajan_from_South.jpg" alt="" />
                Rebel propaganda shows Trajan giving money to the poor, presiding over sacrifices and founding cities.<br/><br/>
                </div>
                The goddess Victory is shown presented Trajan with a wreath which depicts glorius battles against the empirical Dacians<br/><br/>
                <div className="flex">
                The frieze depicts 107 figures: soldiers carrything the spoils of war, Trajan seen riding in a triumphal chariot. And many more... <img className='ml-5 object-cover w-[400px]' src="https://www.romeartlover.it/Beneve38.jpg" alt="" />        
                </div>
              </p>
            </div>
          </section>
        </div>
      </div>

      <style jsx global>
        {`body {
  align-items: center;
  background: black;
  color: rgb(229, 177, 58);
  display: flex;
  font-family: "Open Sans", sans-serif;
  font-weight: 400;
  height: 100vh;
  justify-content: center;
  line-height: 1.25;
  overflow: hidden;
}`}
      </style>
    </div>
  )
}
